//! Search index for FDA guidance documents.
//!
//! Embeds the cleaned JSON at compile time. Provides scored search,
//! lookup by slug, category listing, URL retrieval, and status filtering.

use crate::types::{FdaGuidanceDoc, FdaGuidanceError};

/// Embedded FDA guidance data (generated by `fda-guidance refresh`)
const FDA_GUIDANCE_DATA: &str = include_str!("../data/fda_guidance.json");

/// Load all documents from the embedded index.
pub fn load_all() -> Result<Vec<FdaGuidanceDoc>, FdaGuidanceError> {
    serde_json::from_str(FDA_GUIDANCE_DATA).map_err(|e| FdaGuidanceError::ParseIndex(e.to_string()))
}

/// Score a single document against a query.
#[inline]
fn score_doc(doc: &FdaGuidanceDoc, query_lower: &str, query_terms: &[&str]) -> f64 {
    let mut score = 0.0;

    // Slug exact match
    if doc.slug.to_lowercase() == query_lower {
        score += 100.0;
    }

    // Title contains full query
    let title_lower = doc.title.to_lowercase();
    if title_lower.contains(query_lower) {
        score += 50.0;
    }

    // Topic match
    score += doc
        .topics
        .iter()
        .filter(|t| t.to_lowercase().contains(query_lower))
        .count() as f64
        * 20.0;

    // Product/center match
    score += doc
        .products
        .iter()
        .filter(|p| p.to_lowercase().contains(query_lower))
        .count() as f64
        * 10.0;

    score += doc
        .centers
        .iter()
        .filter(|c| c.to_lowercase().contains(query_lower))
        .count() as f64
        * 10.0;

    // Per-term title keyword matching
    score += query_terms
        .iter()
        .filter(|t| title_lower.contains(*t))
        .count() as f64
        * 2.0;

    score
}

/// Search guidance documents with optional filters.
pub fn search(
    query: &str,
    center: Option<&str>,
    product: Option<&str>,
    status: Option<&str>,
    limit: usize,
) -> Result<Vec<FdaGuidanceDoc>, FdaGuidanceError> {
    let all = load_all()?;
    let query_lower = query.to_lowercase();
    let query_terms: Vec<&str> = query_lower.split_whitespace().collect();

    let mut scored: Vec<(FdaGuidanceDoc, f64)> = all
        .into_iter()
        .filter(|doc| {
            center.is_none_or(|c| doc.centers.iter().any(|dc| dc.eq_ignore_ascii_case(c)))
        })
        .filter(|doc| {
            product.is_none_or(|p| {
                doc.products
                    .iter()
                    .any(|dp| dp.to_lowercase().contains(&p.to_lowercase()))
            })
        })
        .filter(|doc| status.is_none_or(|s| doc.status.eq_ignore_ascii_case(s)))
        .map(|doc| {
            let s = score_doc(&doc, &query_lower, &query_terms);
            (doc, s)
        })
        .filter(|(_, s)| *s > 0.0)
        .collect();

    scored.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));
    scored.truncate(limit);

    Ok(scored.into_iter().map(|(doc, _)| doc).collect())
}

/// Get a document by slug (exact or prefix match).
pub fn get(id: &str) -> Result<Option<FdaGuidanceDoc>, FdaGuidanceError> {
    let all = load_all()?;
    let id_lower = id.to_lowercase();

    // Exact slug match first
    if let Some(doc) = all.iter().find(|d| d.slug.to_lowercase() == id_lower) {
        return Ok(Some(doc.clone()));
    }

    // Prefix match on slug
    if let Some(doc) = all
        .iter()
        .find(|d| d.slug.to_lowercase().starts_with(&id_lower))
    {
        return Ok(Some(doc.clone()));
    }

    // Partial title match (case-insensitive)
    let found = all
        .into_iter()
        .find(|d| d.title.to_lowercase().contains(&id_lower));

    Ok(found)
}

/// Category counts for FDA centers.
pub fn categories_by_center(docs: &[FdaGuidanceDoc]) -> Vec<(String, usize)> {
    let mut counts = std::collections::HashMap::<String, usize>::new();
    for doc in docs {
        for center in &doc.centers {
            *counts.entry(center.clone()).or_insert(0) += 1;
        }
    }
    let mut sorted: Vec<_> = counts.into_iter().collect();
    sorted.sort_by(|a, b| b.1.cmp(&a.1));
    sorted
}

/// Category counts for product areas.
pub fn categories_by_product(docs: &[FdaGuidanceDoc]) -> Vec<(String, usize)> {
    let mut counts = std::collections::HashMap::<String, usize>::new();
    for doc in docs {
        for product in &doc.products {
            *counts.entry(product.clone()).or_insert(0) += 1;
        }
    }
    let mut sorted: Vec<_> = counts.into_iter().collect();
    sorted.sort_by(|a, b| b.1.cmp(&a.1));
    sorted
}

/// Category counts for topics.
pub fn categories_by_topic(docs: &[FdaGuidanceDoc]) -> Vec<(String, usize)> {
    let mut counts = std::collections::HashMap::<String, usize>::new();
    for doc in docs {
        for topic in &doc.topics {
            *counts.entry(topic.clone()).or_insert(0) += 1;
        }
    }
    let mut sorted: Vec<_> = counts.into_iter().collect();
    sorted.sort_by(|a, b| b.1.cmp(&a.1));
    sorted
}

/// Get documents filtered by status and optionally open-for-comment.
pub fn by_status(
    status_filter: &str,
    open_for_comment_only: bool,
) -> Result<Vec<FdaGuidanceDoc>, FdaGuidanceError> {
    let all = load_all()?;
    let filtered: Vec<_> = all
        .into_iter()
        .filter(|d| d.status.eq_ignore_ascii_case(status_filter))
        .filter(|d| !open_for_comment_only || d.open_for_comment)
        .collect();
    Ok(filtered)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_all_has_documents() {
        let docs = load_all().unwrap();
        assert!(
            docs.len() >= 2700,
            "Expected 2700+ docs, got {}",
            docs.len()
        );
    }

    #[test]
    fn test_search_pharmacovigilance() {
        let results = search("pharmacovigilance", None, None, None, 10).unwrap();
        assert!(
            !results.is_empty(),
            "Should find pharmacovigilance-related docs"
        );
    }

    #[test]
    fn test_search_with_center_filter() {
        let results = search("safety", Some("CDER"), None, None, 10).unwrap();
        for doc in &results {
            assert!(
                doc.centers.iter().any(|c| c == "CDER"),
                "All results should be from CDER"
            );
        }
    }

    #[test]
    fn test_search_with_status_filter() {
        let results = search("guidance", None, None, Some("Final"), 10).unwrap();
        for doc in &results {
            assert_eq!(doc.status, "Final", "All results should be Final");
        }
    }

    #[test]
    fn test_get_not_found() {
        let result = get("zzz-nonexistent-slug-zzz").unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn test_categories_by_center() {
        let docs = load_all().unwrap();
        let cats = categories_by_center(&docs);
        assert!(!cats.is_empty());
        // CDER should have the most documents
        assert_eq!(cats[0].0, "CDER", "CDER should be the largest center");
    }

    #[test]
    fn test_by_status_draft() {
        let drafts = by_status("Draft", false).unwrap();
        for d in &drafts {
            assert_eq!(d.status, "Draft");
        }
    }
}
